#! /bin/bash

#define icons for workspaces 1-9
# ic=(0     		     )
# ic=(0 1 2 3 4 5 6 7 8 9)
ic=(0 一 二 三 四 五 六 七 八 九 〇)

#initial check for occupied workspaces
for num in $(hyprctl workspaces -j | jq -r '.[].name'); do
  export o"$num"="$num"
done

#initial check for focused workspace + its monitor
mon=$(hyprctl monitors -j | jq -r '.[] | select(.focused) | .name')
num=$(hyprctl monitors -j | jq -r '.[] | select(.focused) | .activeWorkspace.name')
export f"$num"="$num"
export fnum=f"$num"

workspaces() {
  local ev="${1%%>>*}"
  local data="${1#*>>}"
  case "$ev" in
    workspace)
      [[ "$data" == special* ]] && return #ignore special workspaces
      unset -v "$fnum"
      num="$data"
      export f"$num"="$num"
      export fnum=f"$num"
      ;;
    focusedmon) #set focused workspace following monitor focus change
      unset -v "$fnum"
      mon="${data%%,*}"
      num="${data##*,}"
      export f"$num"="$num"
      export fnum=f"$num"
      ;;
    moveworkspace) #set focused workspace following swapactiveworkspaces
      [[ "${data##*,}" == "$mon" ]] || return
      unset -v "$fnum"
      num="${data%%,*}"
      export f"$num"="$num"
      export fnum=f"$num"
      ;;
    createworkspace) #set occupied workspace
      num="$data"
      export o"$num"="$num"
      ;;
    destroyworkspace) #unset unoccupied workspace
      num="$data"
      unset -v o"$num"
      ;;
  esac
}
module() {
#output eww widget
echo 	"(eventbox :onscroll \"echo {} | sed -e 's/up/-1/g' -e 's/down/+1/g' | xargs hyprctl dispatch workspace\" \
          (box	:class \"works\"	:orientation \"h\" :spacing 5 :space-evenly \"false\" :valign \"center\"	\
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/themes/winter/scripts/workspace 1\'\" :onrightclick \"hyprctl dispatch workspace 1 && $HOME/.config/hypr/themes/winter/scripts/default_app\" :class \"ws-btn 0$o1$f1\" \"${ic[1]}\") \
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/themes/winter/scripts/workspace 2\'\" :onrightclick \"hyprctl dispatch workspace 2 && $HOME/.config/hypr/themes/winter/scripts/default_app\" :class \"ws-btn 0$o2$f2\" \"${ic[2]}\") \
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/themes/winter/scripts/workspace 3\'\" :onrightclick \"hyprctl dispatch workspace 3 && $HOME/.config/hypr/themes/winter/scripts/default_app\" :class \"ws-btn 0$o3$f3\" \"${ic[3]}\") \
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/themes/winter/scripts/workspace 4\'\" :onrightclick \"hyprctl dispatch workspace 4 && $HOME/.config/hypr/themes/winter/scripts/default_app\" :class \"ws-btn 0$o4$f4\" \"${ic[4]}\") \
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/themes/winter/scripts/workspace 5\'\" :onrightclick \"hyprctl dispatch workspace 5 && $HOME/.config/hypr/themes/winter/scripts/default_app\" :class \"ws-btn 0$o5$f5\" \"${ic[5]}\") \
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/themes/winter/scripts/workspace 6\'\" :onrightclick \"hyprctl dispatch workspace 6 && $HOME/.config/hypr/themes/winter/scripts/default_app\" :class \"ws-btn 0$o6$f6\" \"${ic[6]}\") \
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/themes/winter/scripts/workspace 7\'\" :onrightclick \"hyprctl dispatch workspace 7 && $HOME/.config/hypr/themes/winter/scripts/default_app\" :class \"ws-btn 0$o7$f7\" \"${ic[7]}\") \
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/themes/winter/scripts/workspace 8\'\" :onrightclick \"hyprctl dispatch workspace 8 && $HOME/.config/hypr/themes/winter/scripts/default_app\" :class \"ws-btn 0$o8$f8\" \"${ic[8]}\") \
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/themes/winter/scripts/workspace 9\'\" :onrightclick \"hyprctl dispatch workspace 9 && $HOME/.config/hypr/themes/winter/scripts/default_app\" :class \"ws-btn 0$o9$f9\" \"${ic[9]}\") \
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/themes/winter/scripts/workspace 10\'\" :onrightclick \"hyprctl dispatch workspace 10 && $HOME/.config/hypr/themes/winter/scripts/default_app\" :class \"ws-btn 0$o10$f10\" \"${ic[10]}\") \
          )\
        )"
}

module

socat -u UNIX-CONNECT:"${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do
workspaces "$event"
module
done
